### ISSUE TITLE
BME280???

### ISSUE THREAD

**Issue by MFernflower** [genspace/openplant-incubator#2]
https://www.adafruit.com/product/2652

Despite the fact that it's 20 dollars for the sensor it might be worth updating the code to use a single bme280 in the center of the incubator box to check the environment  - it can also sense barometric pressure if one is interested 

I think it's worth the upfront price as only one i2c sensor is needed to monitor the whole incubator environment!

**Comment by danwchan** [comment]
The current code assume the use of the SHT31 sensor which can measure the temperature and humidity. There is no direct control over humidity and likely the plants experience a different humidity in their sealed petri dishes so I view the humidity data as extraneous (even though I collect it). I think the sensing of pressure is similarly extraneous.

I recently updated the code however which would make adapting the incubator to other hardware options easier. I won't be incorporating the BME280 sensor into the build without better rationale, but if you want to use that component now would be a good time to fork the project and edit the code.
